@startuml

start

:Login;

if (Login berhasil?) then (Ya)

:Masuk Dashboard;

if (Pilih Menu?) then (Kelola Data)

:Tambah/Edit/Hapus/Cari Data;

:Simpan perubahan;

else (Lihat Akademik)

:Lihat Informasi Mahasiswa;

endif

:Logout;

else (Tidak)

:Tampilkan pesan gagal login;

endif

stop

@enduml