@startuml

actor Admin
participant Sistem
database Database

Admin -> Sistem : Login
Sistem -> Database : Verifikasi akun
Database --> Sistem : Data valid
Sistem --> Admin : Dashboard tampil

Admin -> Sistem : Tambah mahasiswa

Sistem -> Database : Simpan data mahasiswa

Database --> Sistem : Data berhasil disimpan

Sistem --> Admin : Tampilkan data terbaru

Admin -> Sistem : Edit/Hapus Data

Sistem -> Database : Update/Delete data

Database --> Sistem : Berhasil

Sistem --> Admin : Data diperbarui

@enduml