@startuml UseCase_Diagram
title Use Case Diagram - Sistem Pengelolaan Data Mahasiswa

left to right direction

actor Mahasiswa
actor Admin

rectangle "Sistem Pengelolaan Data Mahasiswa" {

  usecase "Registrasi Akun" as UC1
  usecase "Login" as UC2
  usecase "Lihat Profil" as UC3
  usecase "Ajukan Perubahan Data" as UC4
  usecase "Logout" as UC5

  usecase "Verifikasi Mahasiswa" as UC6
  usecase "Kelola Data Mahasiswa" as UC7
  usecase "Cetak Laporan" as UC8
  usecase "Verifikasi Perubahan Data" as UC12

  usecase "Tambah Data" as UC9
  usecase "Edit Data" as UC10
  usecase "Hapus Data" as UC11
}

Mahasiswa --> UC1
Mahasiswa --> UC2
Mahasiswa --> UC3
Mahasiswa --> UC4
Mahasiswa --> UC5

Admin --> UC2
Admin --> UC6
Admin --> UC7
Admin --> UC8
Admin --> UC12
Admin --> UC5

UC7 .> UC9 : <<include>>
UC7 .> UC10 : <<include>>
UC7 .> UC11 : <<include>>

UC4 .> UC12 : <<include>>

@enduml